#pragma once

#include <cstdint>
#include <string>

enum achievement_e : uint16_t {
	ACHIEVEMENT_NONE,
	ACHIEVEMENT_TRAVELERS_JOURNEY,
	ACHIEVEMENT_THE_LONG_AND_WINDING_ROAD,
	ACHIEVEMENT_HIGHWAY_TO_HELL,
	ACHIEVEMENT_WELCOME_TO_THE_JUNGLE,
	ACHIEVEMENT_SAIL_AWAY,
	ACHIEVEMENT_DESERT_ROSE,
	ACHIEVEMENT_ISLAND_IN_THE_SUN,
	ACHIEVEMENT_TAKE_ME_HOME,
	ACHIEVEMENT_COLD_AS_ICE,
	ACHIEVEMENT_CRACKS_IN_THE_PAVEMENT,
	ACHIEVEMENT_DIRT_ROAD_ANTHEM,
	ACHIEVEMENT_REVEALING_THE_UNKNOWN,
	ACHIEVEMENT_THE_NIGHTS_WATCH,
	ACHIEVEMENT_ALL_SEEING_EYE,
	ACHIEVEMENT_EYE_SEE_YOU,
	ACHIEVEMENT_PAPER_VIEW,
	ACHIEVEMENT_MAPQUEST,
	ACHIEVEMENT_WATCHMEN,
	ACHIEVEMENT_KEY_TO_VICTORY,
	ACHIEVEMENT_ONE_MAN_ARMY,
	ACHIEVEMENT_LAST_HOPE,
	ACHIEVEMENT_GOING_CAMPING,
	ACHIEVEMENT_MONEY_ON_MY_MIND,
	ACHIEVEMENT_SHINE_BRIGHT_LIKE_A_DIAMOND,
	ACHIEVEMENT_ITS_LIKE_WORKING_WITH_MERCURY,
	ACHIEVEMENT_CRYSTAL_CLEAR,
	ACHIEVEMENT_TIMBER,
	ACHIEVEMENT_OREIGINAL_RECIPE,
	ACHIEVEMENT_TREASURE_HUNTER,
	ACHIEVEMENT_WISE_WARRIOR,
	ACHIEVEMENT_PVPWNAGE,
	ACHIEVEMENT_MINE_OVER_MATTER,
	ACHIEVEMENT_ORESON_WELLS,
	ACHIEVEMENT_WOODY_HARRELSON,
	ACHIEVEMENT_GEM_CARREY,
	ACHIEVEMENT_FREDDIE_MERCURY,
	ACHIEVEMENT_BILLY_CRYSTAL,
	ACHIEVEMENT_JEFF_GOLDBLUM,
	ACHIEVEMENT_BILBO_BAGGINS,
	ACHIEVEMENT_FORT_KNOX,
	ACHIEVEMENT_CASTLEMANIA,
	ACHIEVEMENT_MAXIMUM_FORTIFICATION,
	ACHIEVEMENT_WOLF_OF_WALLSTREET,
	ACHIEVEMENT_HUMBLE_BEGINNINGS,
	ACHIEVEMENT_THE_WARRIORS_DEN,
	ACHIEVEMENT_BARRACKS_AND_BEYOND,
	ACHIEVEMENT_FORGE_OF_CHAMPIONS,
	ACHIEVEMENT_MONSTERS_ROOST,
	ACHIEVEMENT_BEHEMOTHS_BIRTHPLACE,
	ACHIEVEMENT_ARCHITECT_OF_DESTINY,
	ACHIEVEMENT_OH_CAPTAIN_MY_CAPTAIN,
	ACHIEVEMENT_TOWER_DEFENSE,
	ACHIEVEMENT_DIMENSIONAL_DRIFT,
	ACHIEVEMENT_ANCIENT_SECRETS,
	ACHIEVEMENT_I_DREAM_OF_GENIE,
	ACHIEVEMENT_HOLY_FOUNDATIONS,
	ACHIEVEMENT_ENCHANTED_EXPANSION,
	ACHIEVEMENT_THE_GRAND_ARCHIVE,
	ACHIEVEMENT_BLOOD_SWEAT_AND_STONE,
	ACHIEVEMENT_MORDOR_EXPANSION_PROJECT,
	ACHIEVEMENT_TOMBSTONE_BOOMTOWN,
	ACHIEVEMENT_CLOUD_OF_DEATH,
	ACHIEVEMENT_TOWNSHIP,
	ACHIEVEMENT_CONQUISTADOR,
	ACHIEVEMENT_LIBERATOR,
	ACHIEVEMENT_DRAGON_SLAYER,
	ACHIEVEMENT_WANTED,
	ACHIEVEMENT_RNGESUS_TAKE_THE_WHEEL,
	ACHIEVEMENT_RATTLE_AND_ROLL,
	ACHIEVEMENT_GRAVE_CONSEQUENCES,
	ACHIEVEMENT_CHILDREN_OF_THE_NIGHT,
	ACHIEVEMENT_DUST_TO_DUST,
	ACHIEVEMENT_MONSTROSITY_UNLEASHED,
	ACHIEVEMENT_WINGS_OF_DEATH,
	ACHIEVEMENT_GREEN_TIDE_RISING,
	ACHIEVEMENT_WARLORDS_BROOD,
	ACHIEVEMENT_HOWLING_HORDE,
	ACHIEVEMENT_BRIDGE_TROLL_TOLL,
	ACHIEVEMENT_COLDBLOODED,
	ACHIEVEMENT_MONSTER_MASH,
	ACHIEVEMENT_MARCH_OF_THE_BRAVE,
	ACHIEVEMENT_VOLLEY_FIRE,
	ACHIEVEMENT_IRON_DISCIPLINE,
	ACHIEVEMENT_MEDITATIONS_OF_WAR,
	ACHIEVEMENT_CHARGE_OF_THE_VALIANT,
	ACHIEVEMENT_HOLY_RECKONING,
	ACHIEVEMENT_INFERNAL_RECRUITMENT,
	ACHIEVEMENT_DEADLY_SEDUCTION,
	ACHIEVEMENT_SKYBOUND_SENTINELS,
	ACHIEVEMENT_MAZE_RUNNERS,
	ACHIEVEMENT_WINGS_OF_TERROR,
	ACHIEVEMENT_BORN_OF_FIRE,
	ACHIEVEMENT_FEY_AWAKENING,
	ACHIEVEMENT_GUARDIAN_OF_THE_GLADE,
	ACHIEVEMENT_VERDANT_VANGUARD,
	ACHIEVEMENT_NATURES_WRATH,
	ACHIEVEMENT_LIGHT_IN_THE_FOREST,
	ACHIEVEMENT_ASHES_REBORN,
	ACHIEVEMENT_FORGED_FOR_WAR,
	ACHIEVEMENT_MOUNTAINBORN,
	ACHIEVEMENT_GEARS_OF_THE_ARCANE,
	ACHIEVEMENT_WISHES_AND_WARFARE,
	ACHIEVEMENT_MASTERS_OF_THE_MYSTIC_ARTS,
	ACHIEVEMENT_STORMLORDS_CALL,
	ACHIEVEMENT_SHOT_THROUGH_THE_HEART,
	ACHIEVEMENT_I_DREAM_OF_JEANNIE,
	ACHIEVEMENT_BANNERMAN,
	ACHIEVEMENT_FRIENDLY_BARTER,
	ACHIEVEMENT_IMMACULATE_RECEPTION,
	ACHIEVEMENT_IN_FLAMES,
	ACHIEVEMENT_WINTER_IS_COMING,
	ACHIEVEMENT_STORM_DRINKER,
	ACHIEVEMENT_EARTHSHAKER,
	ACHIEVEMENT_CHAOS_THEORY,
	ACHIEVEMENT_BLINDED_BY_THE_LIGHT,
	ACHIEVEMENT_FRIENDLY_FIRE,
	ACHIEVEMENT_QUENCHING_THE_FLAME,
	ACHIEVEMENT_CONDUCTIVE_CRITTERS,
	ACHIEVEMENT_BRAINS_BEATS_BRAWN,
	ACHIEVEMENT_METEORIC_RISE,
	ACHIEVEMENT_GRAVE_MISTAKE,
	ACHIEVEMENT_SECOND_LIFE,
	ACHIEVEMENT_CREATIVE_CASTER,
	ACHIEVEMENT_WATCH_THE_WORLD_BURN,
	ACHIEVEMENT_TURTLING_UP,
	ACHIEVEMENT_MASTER_OF_THE_ARCANE,
	ACHIEVEMENT_ENERGIZER_BUNNY,
	ACHIEVEMENT_MAXED_OUT,
	ACHIEVEMENT_GLASS_CANNON,
	ACHIEVEMENT_IMMOVABLE_OBJECT,
	ACHIEVEMENT_OVERMATCHED,
	ACHIEVEMENT_EQUAL_GROUNDS,
	ACHIEVEMENT_MASSACRE,
	ACHIEVEMENT_THE_REAPER,
	ACHIEVEMENT_ONE_PUNCH_HERO,
	ACHIEVEMENT_TITANIC_SMACKDOWN,
	ACHIEVEMENT_THE_BIGGER_THEY_ARE,
	ACHIEVEMENT_UNBREAKABLE,
	ACHIEVEMENT_OUTLAST,
	ACHIEVEMENT_FLAWLESS_EXECUTION,
	ACHIEVEMENT_HIGH_ROLLER,
	ACHIEVEMENT_MAXIMUM_OVERKILL,
	ACHIEVEMENT_CRUNCHING_NUMBERS

};

enum achievement_type_e : uint8_t {
	ACHIEVEMENT_TYPE_NONE,
	ACHIEVEMENT_TYPE_EXPLORATION,
	ACHIEVEMENT_TYPE_ACQUISITION,
	ACHIEVEMENT_TYPE_CONSTRUCTION,
	ACHIEVEMENT_TYPE_RECRUITMENT,
	ACHIEVEMENT_TYPE_CONQUEST,
	ACHIEVEMENT_TYPE_MIGHT,
	ACHIEVEMENT_TYPE_MAGIC,
	ACHIEVEMENT_TYPE_FEATS, //"feats of heroism"?
	ACHIEVEMENT_TYPE_PVP,
	ACHIEVEMENT_TYPE_COOPERTIVE,
	ACHIEVEMENT_TYPE_META, //for achieving multiple other achievements
};

enum achievement_subtype_e : uint8_t {
	ACHIEVEMENT_SUBTYPE_NONE,
	ACHIEVEMENT_SUBTYPE_GENERAL,
	ACHIEVEMENT_SUBTYPE_TERRAIN_TRAVERSAL,
	ACHIEVEMENT_SUBTYPE_FOG_OF_WAR,
	ACHIEVEMENT_SUBTYPE_GOLD,
	ACHIEVEMENT_SUBTYPE_RESOURCES,
	ACHIEVEMENT_SUBTYPE_CHESTS,
	ACHIEVEMENT_SUBTYPE_ARTIFACTS,
	ACHIEVEMENT_SUBTYPE_PALADIN,
	ACHIEVEMENT_SUBTYPE_SORCERESS,
	ACHIEVEMENT_SUBTYPE_WIZARD,
	ACHIEVEMENT_SUBTYPE_BARBARIAN,
	ACHIEVEMENT_SUBTYPE_WARLOCK,
	ACHIEVEMENT_SUBTYPE_NECROMANCER,
	ACHIEVEMENT_SUBTYPE_DWELLINGS,
	ACHIEVEMENT_SUBTYPE_FACTIONS,
	ACHIEVEMENT_SUBTYPE_ELEMENTAL_DAMAGE
};

enum achievement_category_e : uint8_t {
	ACHIEVEMENT_CATEGORY_NONE,
	ACHIEVEMENT_CATEGORY_OFFLINE_ONLY,
	ACHIEVEMENT_CATEGORY_ONLINE_ONLY,
	ACHIEVEMENT_CATEGORY_OFFLINE_AND_ONLINE,
	ACHIEVEMENT_CATEGORY_STAT,
	ACHIEVEMENT_CATEGORY_HIGH_SCORE
};

struct achievement_t {
	struct achievement_tier_t {
		bool valid = false;
		std::string name;
		uint64_t value = 0;
		int reward = 0;
	};
	achievement_e id = ACHIEVEMENT_NONE;
	achievement_type_e type = ACHIEVEMENT_TYPE_NONE;
	achievement_subtype_e subtype = ACHIEVEMENT_SUBTYPE_NONE;
	achievement_category_e category = ACHIEVEMENT_CATEGORY_NONE;
	std::string name;
	std::string asset_id;
	std::string description;
	QDateTime date_achieved;
	bool achieved = false;
	int point_value = 0;
	std::array<achievement_tier_t, 7> tiers;
};

struct achievement_progress_t {
	achievement_e achievement_id = ACHIEVEMENT_NONE;
	int tier_achieved = -1;
	uint64_t value = 0; 
};

enum cosmetic_item_e : uint16_t {
	COSMETIC_NONE,
	COSMETIC_WHITE_HORSE,
	COSMETIC_CHESTNUT_HORSE,
	COSMETIC_BLACK_HORSE,
	COSMETIC_ZEBRA,
	COSMETIC_RHINO,
	COSMETIC_STAG,
	COSMETIC_SKELETAL_RAPTOR,
	COSMETIC_BASIC_PALADIN_SHIRT,
	COSMETIC_BASIC_ENCHANTRESS_SHIRT,
	COSMETIC_BASIC_WIZARD_SHIRT,
	COSMETIC_BASIC_BARBARIAN_SHIRT,
	COSMETIC_BASIC_WARLOCK_SHIRT,
	COSMETIC_BASIC_NECROMANCER_SHIRT,
	COSMETIC_CRUSADERS_CUIRASS,
	COSMETIC_CRUSADERS_HELMET,
	COSMETIC_CRUSADERS_SHOULDERS,
	COSMETIC_CRUSADERS_LEGPLATES,
	COSMETIC_CRUSADERS_BOOTS,
	COSMETIC_CRUSADERS_BRACERS,
	COSMETIC_CRUSADERS_BELT,
	COSMETIC_CRUSADERS_CAPE,
	COSMETIC_UNDERTAKERS_COWL,
	COSMETIC_UNDERTAKERS_HELM,
	COSMETIC_UNDERTAKERS_SHOULDERS,
	COSMETIC_UNDERTAKERS_LEGPLATES,
	COSMETIC_UNDERTAKERS_BOOTS,
	COSMETIC_UNDERTAKERS_BRACERS,
	COSMETIC_UNDERTAKERS_BELT,
	COSMETIC_UNDERTAKERS_CAPE,
	COSMETIC_DEATH_KNIGHTS_CHESTPIECE,
	COSMETIC_DEATH_KNIGHTS_HORNED_HELM,
	COSMETIC_DEATH_KNIGHTS_PAULDRONS,
	COSMETIC_DEATH_KNIGHTS_PANTS,
	COSMETIC_DEATH_KNIGHTS_GREAVES,
	COSMETIC_DEATH_KNIGHTS_BRACERS,
	COSMETIC_DEATH_KNIGHTS_GIRDLE,
	COSMETIC_DEATH_KNIGHTS_CAPE,
	COSMETIC_SPELLBINDERS_ROBE,
	COSMETIC_SPELLBINDERS_HAT,
	COSMETIC_SPELLBINDERS_PAULDRONS,
	COSMETIC_SPELLBINDERS_PANTS,
	COSMETIC_SPELLBINDERS_BOOTS,
	COSMETIC_SPELLBINDERS_BRACERS,
	COSMETIC_SPELLBINDERS_GIRDLE,
	COSMETIC_SPELLBINDERS_CAPE,
	COSMETIC_COMMANDERS_BREASTPLATE,
	COSMETIC_COMMANDERS_HAT,
	COSMETIC_COMMANDERS_PAULDRONS,
	COSMETIC_COMMANDERS_PANTS,
	COSMETIC_COMMANDERS_BOOTS,
	COSMETIC_COMMANDERS_BRACERS,
	COSMETIC_COMMANDERS_GIRDLE,
	COSMETIC_COMMANDERS_CAPE,
	COSMETIC_DRYADS_BREASTPLATE,
	COSMETIC_DRYADS_HAT,
	COSMETIC_DRYADS_PAULDRONS,
	COSMETIC_DRYADS_PANTS,
	COSMETIC_DRYADS_BOOTS,
	COSMETIC_DRYADS_BRACERS,
	COSMETIC_DRYADS_GIRDLE,
	COSMETIC_DRYADS_CAPE,
	//weapons
	COSMETIC_WEAPON_EMPTY,
	COSMETIC_FOREST_LORDS_WALKING_STICK,
	COSMETIC_FOREST_RANGERS_WALKING_STICK,
	COSMETIC_BISHOPS_STAFF_OF_MERCY,
	COSMETIC_REAPERS_RUNED_SCYTHE,
	COSMETIC_STAFF_OF_THE_ARCHMAGE,
	COSMETIC_ACOLYTES_BONE_STAFF,
	COSMETIC_CORRUPTORS_SWORD_OF_REANIMATION,
	COSMETIC_SWORD_OF_THE_SILVER_DRAGON,
	COSMETIC_DEATH_SPIKE_SWORD,
	COSMETIC_REINFORCED_SHORTSWORD,
	COSMETIC_MARAUDERS_LONGSWORD,
	COSMETIC_KNIGHTS_LONGSWORD,
	COSMETIC_INFANTRY_SHORTSWORD,
	COSMETIC_ICY_FROSTBLADE,
	COSMETIC_DEFENDERS_BLADE,
	COSMETIC_DECAPITATOR_OF_DOOM,
	COSMETIC_CHAOTIC_BACKSTABBER,
	COSMETIC_SPINERIPPER,
	COSMETIC_SWASHBUCKLERS_SHAMSHIR,
	COSMETIC_HAND_OF_DEATH,
	COSMETIC_BARBARIC_BLADE,
	COSMETIC_BRAIN_HACKER,
	COSMETIC_CRUSADERS_GREATSWORD_OF_LIGHT,
	COSMETIC_CORRUPTED_DESTROYER,
	COSMETIC_MAGMATIC_BLADE,
	COSMETIC_GIANTS_SPLIT_BLADE,
	COSMETIC_FIERY_DECAPITATOR,
	COSMETIC_ANGELIC_REDEMPTION,
	COSMETIC_GREATSWORD_OF_THE_UNDERTAKER,
	COSMETIC_ANCIENT_LONGSWORD,
	COSMETIC_HOOKED_LONGSWORD,
	COSMETIC_ENCHANTED_GREATSWORD_OF_THE_ELDERS,
	COSMETIC_ENDER_OF_WORLDS,
	//helms
	COSMETIC_HELM_EMPTY,
	//offhands
	COSMETIC_OFFHAND_EMPTY,
	COSMETIC_FOOTMANS_SHIELD,
	COSMETIC_CAVALIERS_SHIELD,
	COSMETIC_SKELETONS_SHIELD,
	//banner-related
	COSMETIC_BANNER_TATTERED_CLOTH,
	COSMETIC_BANNER_PENNANT,
	COSMETIC_BANNER_GONFALON,
	COSMETIC_SIGIL_GRYPHON,
	COSMETIC_SIGIL_TORTOISE,
	COSMETIC_SIGIL_BEAR,
	COSMETIC_SOLID,
	COSMETIC_CHECKERED,
	COSMETIC_ACCENT_NONE,
	COSMETIC_ACCENT_SWORDS,
	COSMETIC_SIGIL_COLOR_ROYAL_BLUE,
	COSMETIC_SIGIL_COLOR_CRIMSON_RED,
	COSMETIC_OUTLINE_COLOR_ROYAL_BLUE,
	COSMETIC_OUTLINE_COLOR_CRIMSON_RED,
	COSMETIC_ACCENT_COLOR_ROYAL_BLUE,
	COSMETIC_ACCENT_COLOR_CRIMSON_RED
};

enum cosmetic_type_e : uint16_t {
	COSMETIC_TYPE_NONE,
	COSMETIC_TYPE_MOUNT,
	COSMETIC_TYPE_PET,
	COSMETIC_TYPE_WEAPON,
	COSMETIC_TYPE_OFFHAND,
	COSMETIC_TYPE_CHEST,
	COSMETIC_TYPE_HELM,
	COSMETIC_TYPE_SHOULDERS,
	COSMETIC_TYPE_PANTS,
	COSMETIC_TYPE_BOOTS,
	COSMETIC_TYPE_BRACERS,
	COSMETIC_TYPE_BELT,
	COSMETIC_TYPE_CAPE,
	//banner
	COSMETIC_TYPE_BANNER_SHAPE,
	COSMETIC_TYPE_BANNER_SIGIL,
	COSMETIC_TYPE_BANNER_SIGIL_COLOR,
	COSMETIC_TYPE_BANNER_OUTLINE_COLOR,
	COSMETIC_TYPE_BANNER_PATTERN,
	COSMETIC_TYPE_BANNER_ACCENT,
	COSMETIC_TYPE_BANNER_ACCENT_COLOR
};

enum cosmetic_unlock_type_e : uint8_t {
	COSMETIC_UNLOCK_TYPE_NONE,
	COSMETIC_UNLOCK_TYPE_FREE,
	COSMETIC_UNLOCK_TYPE_ACHIEVEMENT_REWARD,
	COSMETIC_UNLOCK_TYPE_COIN_PURCHASE,
	COSMETIC_UNLOCK_TYPE_SPECIAL_REWARD
};

enum cosmetic_set_e : uint16_t {
	COSMETIC_SET_NONE,
	COSMETIC_SET_CRUSADER_1,
	COSMETIC_SET_SORCERESS_1,
	COSMETIC_SET_DEATH_KNIGHT_1,
	COSMETIC_SET_UNDERTAKER_1,
	COSMETIC_SET_SPELLBINDER_1,
	COSMETIC_SET_COMMANDER_1,
	COSMETIC_SET_DRYAD_1,
	COSMETIC_SET_HUNTER,
	COSMETIC_SET_VAMPIRE
};

struct cosmetic_item_t {
	std::string name;
	std::string description;
	std::string asset_id_male;
	std::string asset_id_female;
	cosmetic_item_e item_id = COSMETIC_NONE;
	cosmetic_type_e item_type = COSMETIC_TYPE_NONE;
	cosmetic_unlock_type_e unlock_type = COSMETIC_UNLOCK_TYPE_NONE;
	cosmetic_set_e set = COSMETIC_SET_NONE;
	artifact_rarity_e rarity = RARITY_UNKNOWN;
	int cost = 0;
	int unreal_id = -1;
	bool is_unlocked = false;
};
