#pragma once

#include "core/game.h"

#include <vector>

class client_t;

enum multiplayer_game_type_e : quint8 {
	MULTIPLAYER_GAME_TYPE_NONE,
	MULTIPLAYER_GAME_TYPE_DEATHMATCH,
	MULTIPLAYER_GAME_TYPE_SCENARIO
};

enum multiplayer_deathmatch_update_type_e : quint8 {
	DEATHMATCH_UPDATE_TYPE_NONE,
	DEATHMATCH_UPDATE_TYPE_ALL,
	DEATHMATCH_UPDATE_TYPE_HERO,
	DEATHMATCH_UPDATE_TYPE_TROOPS,
	DEATHMATCH_UPDATE_TYPE_DETAILS
};

enum server_error_e : quint8 {
	ERROR_INVALID_TARGET_COORDINATES,
	ERROR_COORDINATES_NOT_VISIBLE,
	ERROR_INVALID_HERO_ID,
	ERROR_INVALID_HERO_TARGET,
	ERROR_INVALID_HERO_TROOP_SPLIT,
	ERROR_INVALID_HERO_TROOP_MERGE,
	ERROR_INVALID_TOWN_ID,
	ERROR_INVALID_TOWN_TARGET,
	ERROR_INVALID_TOWN_TROOP_SPLIT,
	ERROR_INVALID_TOWN_TROOP_MERGE,
	ERROR_INVALID_TOWN_TROOP_MOVE,
	ERROR_INVALID_TOWN_TROOP_PURCHASE,
	ERROR_INVALID_TOWN_HERO_SWAP,
	ERROR_INVALID_ENUMERATION_VALUE,
	ERROR_INVALID_OBJECT_ID,
	ERROR_INVALID_TROOP_PURCHASE
};

enum client_action_e : quint8 {
	//ACTION_HEARTBEAT = 0,
	ACTION_REQUEST_MAPS_LIST,
	ACTION_REQUEST_MAP_INFO,
	ACTION_REQUEST_ONLINE_PLAYERS_LIST,
	ACTION_ADVENTURE_MAP_END_TURN,
	ACTION_ADVENTURE_MAP_SEND_CHAT_MESSAGE,
	ACTION_ADVENTURE_MAP_QUIT_GAME,
	ACTION_ADVENTURE_MAP_MOVE_HERO,
	ACTION_ADVENTURE_MAP_DISMISS_HERO,
	ACTION_ADVENTURE_MAP_DISMISS_TROOPS,
	ACTION_ADVENTURE_MAP_PICKUP_OBJECT,
	ACTION_ADVENTURE_MAP_INTERACT_WITH_OBJECT,
	ACTION_ADVENTURE_MAP_TRADE_RESOURCES,
	ACTION_ADVENTURE_MAP_GIVE_PLAYER_RESOURCES,
	ACTION_ADVENTURE_MAP_DIALOG_CHOICE,
	ACTION_ADVENTURE_MAP_MOVE_TROOPS_FROM_ARMY_TO_ARMY,
	ACTION_ADVENTURE_MAP_MOVE_TROOPS_WITHIN_ARMY,
	ACTION_ADVENTURE_MAP_MEET_HEROES,

	///
	ACTION_MULTIPLAYER_REQUEST_NEW_GAME,
	ACTION_MULTIPLAYER_RESPONSE_TO_GAME_REQUEST,
	ACTION_MULTIPLAYER_DEATHMATCH_CHANGE,
	ACTION_MULTIPLAYER_READY_UP,
	ACTION_MULTIPLAYER_CANCEL_GAME,

	///
	ACTION_COMBAT_MOVE_TROOP,
	ACTION_COMBAT_ATTACK_TROOP,
	ACTION_COMBAT_WAIT_TROOP,
	ACTION_COMBAT_DEFEND_TROOP,
	ACTION_COMBAT_USE_TROOP_ABILITY,
	ACTION_COMBAT_CAST_SPELL,
	ACTION_COMBAT_RETREAT,
	ACTION_COMBAT_SURRENDER,
	ACTION_COMBAT_CATAPULT_SHOOT_WALL,
	ACTION_BATTLE_ACCEPT_RESULTS,
	ACTION_BATTLE_REPLAY,
	///
	ACTION_HERO_SPLIT_TROOPS,
	ACTION_HERO_MERGE_TROOPS,
	ACTION_HERO_SWAP_TROOPS,
	ACTION_HERO_COMBINE_TROOPS,
	//ACTION_HERO_MOVE_TROOPS,
	ACTION_HERO_HERO_MOVE_TROOPS,
	ACTION_HERO_HERO_MOVE_ARMY,
	ACTION_HERO_HERO_MOVE_TROOP_STACK,
	ACTION_HERO_HERO_MOVE_ALL_ARTIFACTS,
	ACTION_HERO_HERO_MOVE_ARTIFACT,
	ACTION_HERO_HERO_MOVE_ARTIFACT_FROM_SLOT_TO_BACKPACK,
	ACTION_HERO_HERO_MOVE_ARTIFACT_FROM_BACKPACK_TO_SLOT,
	ACTION_HERO_HERO_MOVE_ARTIFACT_TO_BACKPACK_SLOT,
	ACTION_HERO_HERO_SWAP_EVERYTHING,
	ACTION_HERO_HERO_SWAP_ARMIES,
	ACTION_HERO_HERO_SWAP_ARTIFACTS,
	ACTION_HERO_SELECT_LEVELUP_SKILL,
	//ACTION_HERO_MOVE_ARTIFACT,
	ACTION_HERO_MOVE_ARTIFACTS_IN_BACKPACK,
	ACTION_HERO_MOVE_ARTIFACT_FROM_BACKPACK_TO_SLOT,
	ACTION_HERO_MOVE_ARTIFACT_TO_BACKPACK_FROM_SLOT,
	ACTION_HERO_MOVE_ARTIFACT_FROM_BACKPACK_SLOT_FROM_SLOT,
	ACTION_HERO_MOVE_ARTIFACTS_IN_PAPERDOLL_SLOT,
	ACTION_HERO_MOVE_ARTIFACT_TO_BACKPACK_SLOT_FROM_SLOT,

	ACTION_TOWN_SPLIT_TROOPS,
	ACTION_TOWN_MERGE_TROOPS,
	ACTION_TOWN_SWAP_TROOPS,
	ACTION_TOWN_MOVE_TROOPS,
	ACTION_TOWN_BUY_TROOPS,
	ACTION_TOWN_BUILD,
	ACTION_TOWN_DISMISS_TROOPS,
	ACTION_TOWN_GARRISON_HERO,
	ACTION_TOWN_UNGARRISON_HERO,
	ACTION_TOWN_SWAP_VISITING_AND_GARRISONED_HEROES,
	ACTION_TOWN_MOVE_ALL_TROOPS_FROM_VISITING_HERO_TO_GARRISON,
	ACTION_TOWN_MOVE_ALL_TROOPS_FROM_GARRISON_TO_VISITING_HERO,
	ACTION_TOWN_MOVE_TROOP_FROM_GARRISON_TO_VISITING_HERO,
	ACTION_TOWN_MOVE_TROOP_FROM_VISITING_HERO_TO_GARRISON,
	ACTION_TOWN_RECRUIT_HERO,
	
	ACTION_OBJECT_BUY_TROOPS
	
};

enum troop_group_id_e : quint8 {
	TROOP_GROUP_ID_NONE,
	TROOP_GROUP_ID_CREATURE_BUFFER,
	TROOP_GROUP_ID_SELECTED_HERO
};

enum server_response_e : quint8 {
	//RESPONSE_HEARTBEAT = 0,
	RESPONSE_SERVER_ERROR = 0,
	RESPONSE_SERVER_OK,
	RESPONSE_MAPS_LIST,
	RESPONSE_MAP_INFO,
	RESPONSE_ONLINE_PLAYERS_LIST,
	RESPONSE_MULTIPLAYER_REQUEST_NEW_GAME,
	RESPONSE_MULTIPLAYER_GAME_REQUEST_REPLY,
	RESPONSE_MULTIPLAYER_DEATHMATCH_INFO,
	RESPONSE_MULTIPLAYER_DEATHMATCH_SETUP_START,
	RESPONSE_MULTIPLAYER_DEATHMATCH_START,
	RESPONSE_MULTIPLAYER_DEATHMATCH_END,
	RESPONSE_GAME_INFO,
	RESPONSE_CHAT_MESSAGE,
	RESPONSE_MAP_LAYOUT,
	RESPONSE_MAP_TILE_INFO,
	RESPONSE_MAP_DOODAD,
	RESPONSE_MAP_INTERACTABLE_OBJECT,
	RESPONSE_MAP_HERO,
	RESPONSE_MAP_HERO_UPDATE,
	RESPONSE_MAP_HERO_LEVELUP_DIALOG,
	RESPONSE_MAP_SHOW_DIALOG,
	RESPONSE_MAP_REMOVE_INTERACTABLE_OBJECT,
	RESPONSE_MAP_REMOVE_HERO,
	RESPONSE_SHOW_GAME,
	RESPONSE_NEW_DAY,
	RESPONSE_BATTLE_INFO,
	RESPONSE_BATTLE_ACTION,
	RESPONSE_BATTLE_UNIT_UPDATE,
	RESPONSE_BATTLE_UPDATE,
	RESPONSE_BATTLE_FINISHED
};
